project:
  type: book
  output-dir: docs

book:
  title: "ENVS 543 Fall Semester 2024"
  author: "Rodney J. Dyer"
  date: "12/3/2024"
  chapters:
    - index.qmd
    - markdown_narrative.qmd
    - basic_data_narrative.qmd
    - containers_narrative.qmd
    - tidyverse_narrative.qmd
    - functions_narrative.qmd
    - classic_graphics_narrative.qmd
    - ggplot_narrative.qmd
    - points_narrative.qmd
    - raster_narrative.qmd
    - text_narrative.qmd
    - factors_narrative.qmd
    - correlation_narrative.qmd
    - regression_narrative.qmd
    - aov_narrative.qmd
    - counting_stats_narrative.qmd

format:
  html:
    theme: cosmo

editor: source

