project:
  type: book

book:
  title: "ENVS543.2024"
  author: "Rodney J. Dyer"
  date: "12/3/2024"
  chapters:
    - index.qmd
    - markdown_narrative.qmd
    - basic_data_narrative.qmd
    - containers_narrative.qmd
    - tidyverse_narrative.qmd
    - functions_narrative.qmd
    - classic_graphics_narrative.qmd
    - ggplot_narrative.qmd
    - points_narrative.qmd
    - raster_narrative.qmd
    - text_narrative.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

