project:
  type: website
  output-dir: docs

website:
  title: "ENVS 543 Fall Semester 2024"
  navbar: 
    left:
    - text: Basics
      menu: 
      - markdown_narrative.qmd
      - basic_data_narrative.qmd
      - containers_narrative.qmd
      - tidyverse_narrative.qmd
      - functions_narrative.qmd
      - text_narrative.qmd
      - factors_narrative.qmd
    - text: Graphics
      menu: 
      - classic_graphics_narrative.qmd
      - ggplot_narrative.qmd
    - text: Spatial
      menu:
      - points_narrative.qmd
      - raster_narrative.qmd
    - text: Analyses
      menu: 
      - correlation_narrative.qmd
      - regression_narrative.qmd
      - aov_narrative.qmd
      - counting_stats_narrative.qmd

format:
  html:
    theme: cosmo

editor: source

