<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Non-Parametric &amp; Counting Statistics – ENVS 543: Data Literacy (2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ENVS 543: Data Literacy (2024)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Basics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics">    
        <li>
    <a class="dropdown-item" href="./markdown_narrative.html">
 <span class="dropdown-text">Markdown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./basic_data_narrative.html">
 <span class="dropdown-text">Basic Data Types</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./containers_narrative.html">
 <span class="dropdown-text">Basic Data Containers in R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tidyverse_narrative.html">
 <span class="dropdown-text">Tidyverse</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./functions_narrative.html">
 <span class="dropdown-text">Narrative Title</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./text_narrative.html">
 <span class="dropdown-text">Text Based Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./factors_narrative.html">
 <span class="dropdown-text">Factor Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-graphics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Graphics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-graphics">    
        <li>
    <a class="dropdown-item" href="./classic_graphics_narrative.html">
 <span class="dropdown-text">Basic R Graphics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ggplot_narrative.html">
 <span class="dropdown-text">ggplot Graphics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-spatial" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Spatial</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-spatial">    
        <li>
    <a class="dropdown-item" href="./points_narrative.html">
 <span class="dropdown-text">Spatial Point Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./raster_narrative.html">
 <span class="dropdown-text">Raster Data Narrative</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analyses" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Analyses</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analyses">    
        <li>
    <a class="dropdown-item" href="./correlation_narrative.html">
 <span class="dropdown-text">Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression_narrative.html">
 <span class="dropdown-text">Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aov_narrative.html">
 <span class="dropdown-text">Analysis of Variance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./counting_stats_narrative.html">
 <span class="dropdown-text">Non-Parametric &amp; Counting Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#counting-or-non-parametric-statistics" id="toc-counting-or-non-parametric-statistics" class="nav-link active" data-scroll-target="#counting-or-non-parametric-statistics">Counting, or ‘Non-Parametric’ Statistics</a></li>
  <li><a href="#the-binomial-test" id="toc-the-binomial-test" class="nav-link" data-scroll-target="#the-binomial-test">The Binomial Test</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables">Contingency Tables</a></li>
  <li><a href="#ill-expand-this-to-cases-beyond-a-2x2-contingency-below." id="toc-ill-expand-this-to-cases-beyond-a-2x2-contingency-below." class="nav-link" data-scroll-target="#ill-expand-this-to-cases-beyond-a-2x2-contingency-below.">I’ll expand this to cases beyond a 2x2 contingency below.</a>
  <ul class="collapse">
  <li><a href="#the-assumptions" id="toc-the-assumptions" class="nav-link" data-scroll-target="#the-assumptions">The Assumptions</a></li>
  </ul></li>
  <li><a href="#nonparametric-eqivallent-approaches" id="toc-nonparametric-eqivallent-approaches" class="nav-link" data-scroll-target="#nonparametric-eqivallent-approaches">NonParametric Eqivallent Approaches</a>
  <ul class="collapse">
  <li><a href="#spearman-test-for-ranked-correlation" id="toc-spearman-test-for-ranked-correlation" class="nav-link" data-scroll-target="#spearman-test-for-ranked-correlation">Spearman Test for Ranked Correlation</a></li>
  </ul></li>
  <li><a href="#non-parametric-regression" id="toc-non-parametric-regression" class="nav-link" data-scroll-target="#non-parametric-regression">Non-Parametric Regression</a>
  <ul class="collapse">
  <li><a href="#local-regression" id="toc-local-regression" class="nav-link" data-scroll-target="#local-regression"><strong>LO</strong>cal regr<strong>ESS</strong>ion</a></li>
  <li><a href="#fitting-a-loess-model" id="toc-fitting-a-loess-model" class="nav-link" data-scroll-target="#fitting-a-loess-model">Fitting A loess Model</a></li>
  </ul></li>
  <li><a href="#other-regression-approaches" id="toc-other-regression-approaches" class="nav-link" data-scroll-target="#other-regression-approaches">Other Regression Approaches</a>
  <ul class="collapse">
  <li><a href="#mann-whitney-test-for-the-equivallence-of-two-means" id="toc-mann-whitney-test-for-the-equivallence-of-two-means" class="nav-link" data-scroll-target="#mann-whitney-test-for-the-equivallence-of-two-means">Mann-Whitney Test For the Equivallence of Two Means</a></li>
  <li><a href="#kruskal-wallis-test-for-equivallence-of-several-means" id="toc-kruskal-wallis-test-for-equivallence-of-several-means" class="nav-link" data-scroll-target="#kruskal-wallis-test-for-equivallence-of-several-means">Kruskal-Wallis Test for Equivallence of Several Means</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Non-Parametric &amp; Counting Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="media/AnalysisMatrix.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( tidyverse )</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( forcats )</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>( <span class="fu">theme_minimal</span>() ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="counting-or-non-parametric-statistics" class="level2">
<h2 class="anchored" data-anchor-id="counting-or-non-parametric-statistics">Counting, or ‘Non-Parametric’ Statistics</h2>
<p>To date, we’ve been talking about the kinds of statistical approaches we use based upon the kind of data that we have for predictors and responses. Keeping it really simple, the graphic below attempts to capture this dynamic.</p>
<p>In this display, counting statistics are those that have <code>factor</code> data for both predictors and responses. However, the methods that we use in this quadrant, like <span class="math inline">\(\chi^2\)</span> tests, are a small fraction of available methods that we can classify as <em>NonParametric</em> statistics.</p>
<p>Non-parametric counting statistics are essential tools in data analysis because they provide robust methods for understanding data without making strong assumptions about the underlying distribution. Many traditional statistical methods rely on parametric assumptions, such as normality, homoscedasticity, or linearity. However, real-world data often violate these assumptions due to skewness, outliers, or categorical variables. Non-parametric methods excel in these scenarios by leveraging the rank or order of data rather than its precise values, making them ideal for analyzing ordinal data, small sample sizes, or data sets with unknown distributions.</p>
<p>Counting statistics, like chi-square tests, Fisher’s exact test, or Wilcoxon rank-sum tests, allow researchers to test hypotheses about relationships or differences without assuming normality. For example, in environmental studies or survey analysis, datasets may include counts of species occurrences, categorical survey responses, or presence/absence data. Non-parametric methods ensure reliable results in these cases, enabling data-driven decisions even with non-normal or heterogeneous data that extend beyond just the lower right quadrant of the image above.</p>
<p>So let’s start simple and I’ll walk through a set of these kinds of models and highlight how we can apply a non-parametric approach to data whose identity may suggest other parametric statistics would be appropriate but whose normality or properties suggest that we not use those more traditional methods.</p>
</section>
<section id="the-binomial-test" class="level2">
<h2 class="anchored" data-anchor-id="the-binomial-test">The Binomial Test</h2>
<p>We’ve discussed the Binomial as part of the underlying generative functions for Bayesian Statistics already, but let’s revisit it for just a moment to get more specific on its general status. As a reminder, this is a test where the outcomes can be classified into either “Group A” or “Group B” (a 2-level factor in <code>R</code>).</p>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<p>The binomial test assumes:</p>
<ol type="1">
<li>The <span class="math inline">\(n\)</span> samples are mutually independent.<br>
</li>
<li>Each sample has an underlying probability, <span class="math inline">\(p\)</span>, of being classified in “Group A” and a probability of <span class="math inline">\(1-p\)</span> of being assigned to “Group B”.</li>
</ol>
<p>The test statistic for this analysis is the number of values observed in “Group A” as a count. Because we are testing for the value of <span class="math inline">\(p\)</span> (or our confidence in the range of values it can assume), the null hypothesis is:</p>
<p><span class="math inline">\(H_O: p = \hat{p}\)</span></p>
<p>In <code>R</code>, we can test this using the <code>binom.test()</code> function, whose signature is:</p>
<p><img src="media/binomial_signature.png" class="img-fluid"></p>
<p>You can either give the function a single values for <code>x</code> and <code>n</code> or you can have <code>x</code> be a 2-element vector and skip the <code>n</code> part.</p>
<p>Borrowing from a previous example, let’s assume we are sampling fish in the James River. The hypothesis is that the frequency of catfish is</p>
<p><span class="math display">\[
p_{catfish} = \frac{N_{catfish}}{N_{catfish} + N_{other}} = \frac{37}{50} \approx 0.74
\]</span></p>
<p>So, if we were to go out and do some more sampling, the null hypotehsis would be:</p>
<p><span class="math inline">\(H_O: p_{catfish} = 0.74\)</span></p>
<p>Let’s assume you just got back from a great sampling day and found the following data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>catfish <span class="ot">&lt;-</span> <span class="dv">52</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>non_catfish <span class="ot">&lt;-</span> <span class="dv">47</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To test if this sampling exercise is consistent with the previous assumption of a 74% catfish presence, we do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">c</span>( catfish, non_catfish )</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>p_catfish <span class="ot">&lt;-</span> <span class="fl">0.74</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">Counts =</span> <span class="fu">c</span>( samples, <span class="fl">0.74</span> <span class="sc">*</span> <span class="fu">sum</span>(samples), ( (<span class="dv">1</span><span class="fl">-0.74</span>) <span class="sc">*</span> <span class="fu">sum</span>(samples) )),</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Fish =</span> <span class="fu">c</span>(<span class="st">"Catfish"</span>, <span class="st">"Other"</span>, <span class="st">"Catfish"</span>, <span class="st">"Other"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"Observed"</span>,<span class="st">"Observed"</span>, <span class="st">"Expected"</span>, <span class="st">"Expected"</span>) )</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( df, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(Fish,Counts, <span class="at">fill=</span>Group) )<span class="sc">+</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>( <span class="at">position=</span><span class="st">"dodge"</span>, <span class="at">stat=</span><span class="st">"identity"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(<span class="at">x=</span>samples, <span class="at">p =</span> p_catfish )</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fit </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  samples
number of successes = 52, number of trials = 99, p-value = 5.007e-06
alternative hypothesis: true probability of success is not equal to 0.74
95 percent confidence interval:
 0.4223973 0.6265570
sample estimates:
probability of success 
             0.5252525 </code></pre>
</div>
</div>
<p>Whose results suggest that <span class="math inline">\(p_{catfish} \ne 0.74\)</span> and we reject the null hypothesis. Our data subbest, from the samples we provided, that the observed <span class="math inline">\(p_{catfish}\)</span> falls within the interval of 0.422 - 0.627.</p>
<p>For examples with more than two “Group”s, there is a multinomial test as well, but the function is not one built into R and you’ll want to check out the <a href="https://search.r-project.org/CRAN/refmans/EMT/html/multinomial.test.html">Multinomial</a> package for that function.</p>
</section>
</section>
<section id="contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="contingency-tables">Contingency Tables</h2>
<p>Contingency tables are another counting approach, where your data can be classified into one or more categories. Often it is taken as a comparison between populations. So, in keeping with our fish theme, let’s assume we went to another river and did another sampling run on catfish. In general, we are not limited to “Group A” vs “Group B” but we will use it for continuity here.</p>
<p>Our sampling can be categorized as follows for the two populations of samples we’ve collected.</p>
<p><img src="media/ContingencyTable.png" class="img-fluid"></p>
<p>The values above are Observerd counts of observations in each pair of categories. Every fish is talled into the grouping (catfish vs not) and the location it was sampled (population 1 vs population 2). The total number of sampels at each population is <span class="math inline">\(n_1\)</span> (in the data it was $n_1 =$99) and <span class="math inline">\(n_2\)</span> (to be shown below) and the total number of samples that are catfish is <span class="math inline">\(C_1 = O_{11} + O_{21}\)</span> and not catfish as <span class="math inline">\(C_2\)</span> which also happens to be <span class="math inline">\(N - C_1\)</span> (for completeness).</p>
<p>Again, here we have 2 rows and 2 columns, but this can be extended to larger numbers of groupings and sampling population as necessary and the analysis is the same.</p>
<p>In this simple case, the null hypothesis is <strong>not</strong> about the exact value of <span class="math inline">\(p_{catfish}\)</span>, as in the binomial, but rather that the frequency of catfish in <code>Population 1</code>, let’s define this as <span class="math inline">\(p_1\)</span> is equal to the probabilty of sampling a catfish at <code>Population 2</code>, which we define as <span class="math inline">\(p_2\)</span>.</p>
<p><span class="math inline">\(H_O: p_1 = p_2\)</span></p>
</section>
<section id="ill-expand-this-to-cases-beyond-a-2x2-contingency-below." class="level2">
<h2 class="anchored" data-anchor-id="ill-expand-this-to-cases-beyond-a-2x2-contingency-below.">I’ll expand this to cases beyond a 2x2 contingency below.</h2>
<section id="the-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="the-assumptions">The Assumptions</h3>
<p>The assumptions for a contingency table analysis are:</p>
<ol type="1">
<li>Each sampling is a random sample.<br>
</li>
<li>Any pair of samples are mutually independent.<br>
</li>
<li>Each sample is unambiguously categorized into one, and only one, Grouping and Replicate.</li>
</ol>
<p>To run this test in <code>R</code> we use the <code>chisq.test()</code> function, whose signature is as follows:</p>
<p><img src="media/chisq_signature.png" class="img-fluid"></p>
<p>Where for our example, we will use it by passing a 2x2 matrix of observations as <code>x</code>. Let’s say I went out to another site and did 50 more samples and found 32 catfish.</p>
<p>Here is a matrix with these numbers. I’m going to decorate it with row and column labels for clarity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Observed <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">52</span>, <span class="dv">47</span>, <span class="dv">32</span>, <span class="dv">18</span>), <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( Observed ) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Population 1"</span>, <span class="st">"Population 2"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( Observed ) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Catfish"</span>, <span class="st">"Other"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>Observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Catfish Other
Population 1      52    47
Population 2      32    18</code></pre>
</div>
</div>
<p>Our expectations are based on the <span class="math inline">\(p_{catfish} = 0.74\)</span> and can be used to create an Expected value for each of the cells in the matrix above. For example, the expected value for the number of catfish from Population 1 would be <span class="math inline">\(n_1 * 0.74\)</span> and for non-catfish would be <span class="math inline">\((1-0.74) * n_1\)</span>. We can do the same for the second site.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="dv">52</span> <span class="sc">+</span> <span class="dv">47</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">32</span> <span class="sc">+</span> <span class="dv">18</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>Expected <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="fu">c</span>( <span class="fl">0.74</span> <span class="sc">*</span> n1, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span><span class="fl">-0.74</span>) <span class="sc">*</span> n1, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">0.74</span> <span class="sc">*</span> n2,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span><span class="fl">-0.74</span>) <span class="sc">*</span> n2), <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( Expected ) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Population 1"</span>, <span class="st">"Population 2"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( Expected ) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Catfish"</span>, <span class="st">"Other"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>Expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Catfish Other
Population 1   73.26 25.74
Population 2   37.00 13.00</code></pre>
</div>
</div>
<p>So, in some sense, we set the underlying probability of catfish in either locale to <span class="math inline">\(0.74\)</span>. If the observed values are close to the expected, then the data would be consistent with what is expected from the underlying hypothesis. If they are not close, then the data data are deviating. The amount of deviation is what we will be using as a test statistic here and it is a measure of:</p>
<ol type="1">
<li>How far apart <span class="math inline">\(O_{xy}\)</span> is from <span class="math inline">\(E_{xy}\)</span>,</li>
<li>Standardized by the magnitude of the <span class="math inline">\(E_{xy}\)</span>.</li>
</ol>
<p>Giving us the test statistic:</p>
<p><span class="math display">\[
T = \sum_{i=1}^r\sum_{j=1}^c\frac{(O_{ij} - E_{ij})^2}{E_{ij}}
\]</span></p>
<p>The subscripts account for the number of rows (<span class="math inline">\(r\)</span>) and columns (<span class="math inline">\(c\)</span>) for any arbitrary sized table beyond the 2x2 example we have here. We can estimate the test statistic in R direclty, as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">sum</span>(  (Observed <span class="sc">-</span> Expected)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> Expected )</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26.32813</code></pre>
</div>
</div>
<p>This test statistic is expected to be equivalent to a <span class="math inline">\(\Chi^2\)</span> statistic with <span class="math inline">\((r-1)(c-1)\)</span> degrees of freedom. We haven’t really estimated this directly yet, so here is how you’d figure out the probability of this test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">1.0</span> <span class="sc">-</span> alpha </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>critical.value <span class="ot">&lt;-</span> <span class="fu">qchisq</span>( p ,<span class="dv">1</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>critical.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.841459</code></pre>
</div>
</div>
<p>You’ve probably seen this value before; it is a common one that we use in teaching basic Biology courses when we do Mendel’s pea phenotypes. So, the test statistic is $T =$26.3281253 and the critical value is 3.8414588, so we would <em>Reject H_O</em> that the fraction of catfish/not-catfish from <em>Population 1</em> is not the same as observed in <em>Population 2</em>.</p>
<p>But, we are still stuck with the <span class="math inline">\(\alpha = 0.05\)</span> issue and we’d probably rather have the actual p-value for the observed Test statistic, <span class="math inline">\(T\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> <span class="fl">1.0</span> <span class="sc">-</span> <span class="fu">pchisq</span>( T, <span class="at">df=</span><span class="dv">1</span> )</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.88063e-07</code></pre>
</div>
</div>
<p>Notice I’ve used the <code>qschisq</code> function to get hte critcal value for some probability and the <code>pchisq</code> to the probability associated with an observed value. Every distribution has <code>p*</code> and <code>q*</code> functions associated with them and can be used to find critical values and probabilities if you need to do it manually.</p>
<p>In the real world, you’ll probably be taking the data from a larger <code>data.frame</code> object where you collected additional data. Here is a sample, where the species and location are factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">Sample =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">149</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Species =</span> <span class="fu">factor</span>( <span class="fu">c</span>( <span class="fu">rep</span>(<span class="st">"Catfish"</span>, <span class="dv">52</span>), <span class="fu">rep</span>(<span class="st">"Other"</span>, <span class="dv">47</span>), </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="fu">rep</span>(<span class="st">"Catfish"</span>, <span class="dv">32</span>), <span class="fu">rep</span>(<span class="st">"Other"</span>,<span class="dv">18</span>) ) ),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Site =</span> <span class="fu">factor</span>( <span class="fu">c</span>( <span class="fu">rep</span>(<span class="st">"Population 1"</span>, <span class="dv">99</span>), <span class="fu">rep</span>(<span class="st">"Population 2"</span>, <span class="dv">50</span>))),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Measurement =</span> <span class="fu">rnorm</span>(<span class="dv">149</span>,<span class="at">mean=</span><span class="dv">12</span>, <span class="at">sd=</span><span class="dv">3</span>))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( df )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Sample       Species             Site     Measurement    
 Min.   :  1   Catfish:84   Population 1:99   Min.   : 5.074  
 1st Qu.: 38   Other  :65   Population 2:50   1st Qu.: 9.803  
 Median : 75                                  Median :12.076  
 Mean   : 75                                  Mean   :12.158  
 3rd Qu.:112                                  3rd Qu.:14.324  
 Max.   :149                                  Max.   :20.175  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sample Species         Site Measurement
1      1 Catfish Population 1   12.298630
2      2 Catfish Population 1   15.180844
3      3 Catfish Population 1   16.319885
4      4 Catfish Population 1    9.803299
5      5 Catfish Population 1   11.980147
6      6 Catfish Population 1    8.229584</code></pre>
</div>
</div>
<p>It is easy to grab the tabular data, and configure it as we did above using the <code>table()</code> functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( df<span class="sc">$</span>Site, df<span class="sc">$</span>Species )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              
               Catfish Other
  Population 1      52    47
  Population 2      32    18</code></pre>
</div>
</div>
<p>There are a few caveats that we need to make here. First, this appraoch requires that we have a sufficient number of observations in each of the cells. The longest running recommendation comes form Cochran<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, who suggested that any time you have an <span class="math inline">\(E_{ij} \le 1\)</span> or if more than 20% of the <span class="math inline">\(E_{ij} \le 5\)</span>, there may be some issues with statistical power and the approximation for the <span class="math inline">\(\Chi^2\)</span> statistic may be poor. In those cases, perhaps a permutation approach would be more appropriate.</p>
</section>
</section>
<section id="nonparametric-eqivallent-approaches" class="level2">
<h2 class="anchored" data-anchor-id="nonparametric-eqivallent-approaches">NonParametric Eqivallent Approaches</h2>
<p>I’m going to use a couple of examples here to show how we can use counting statistics and ranks for methods where we intended to use parametric approaches like a t-test, correlation, regression, and analysis of variance but the data were not suitable for those methods.</p>
<section id="spearman-test-for-ranked-correlation" class="level3">
<h3 class="anchored" data-anchor-id="spearman-test-for-ranked-correlation">Spearman Test for Ranked Correlation</h3>
<p>When we discussed correlation data (e.g., continuous predictors and response variables), I did point out that there was another kind of correlation statistic that uses ranks (the <code>mode="spearman"</code>) instead of the raw data (the Pearson-Product Moment approach which is the default). As we saw before, there is an option in the normal <code>cor.test</code> function that allows you to use a rank-based analysis instead of the normal Pearson Product-Moment approach.</p>
<p><img src="media/cor.test_signature.png" class="img-fluid"></p>
<p>This approach, basically, orders the magnitude of both predictor and response and assigns a rank (e.g., <span class="math inline">\(1^{st}, 2^{nd}, \ldots N^{th}\)</span>) for both variables and then estimates the relationship by correlating the ranked values instead of the raw values.</p>
<p>For brevity, I’ll not give an example and have you look back at the correlation lecture for more information.</p>
</section>
</section>
<section id="non-parametric-regression" class="level2">
<h2 class="anchored" data-anchor-id="non-parametric-regression">Non-Parametric Regression</h2>
<p>There are a few different methods for estimating linear regression models via non-parametric approaches. We’ve seen one common approach whenever we used the <code>stat_smooth()</code> function in <code>ggplot()</code>. By default, it uses the <code>loess()</code> local smoother approach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(Sepal.Length, Sepal.Width) ) <span class="sc">+</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In a <code>lm()</code>, the goal is to use least cost approaches to minimize the error variance across all the data simultaneously.</p>
<p><img src="media/lm_error.png" class="img-fluid"></p>
<section id="local-regression" class="level3">
<h3 class="anchored" data-anchor-id="local-regression"><strong>LO</strong>cal regr<strong>ESS</strong>ion</h3>
<p>The <code>loess()</code> approach looks at a local window for estimating the formula of the line along with a moderatly high-dimensional polynomial.</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta}_O^{x} + \hat{\beta}_1^{x}x_i
\]</span></p>
<p>The function has a signature similar to that we saw in <code>lm()</code> for normal <a href="https://dyerlabteaching.github.io/Regression/narrative.html">regression</a>.</p>
<p><img src="media/loess_signature.png" class="img-fluid"></p>
<p>Notice the optional value for <code>span</code>, which defines the size of the local window.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-a-loess-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-loess-model">Fitting A loess Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">loess</span>( Sepal.Width <span class="sc">~</span> Sepal.Length, <span class="at">data=</span>iris)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
loess(formula = Sepal.Width ~ Sepal.Length, data = iris)

Number of Observations: 150 
Equivalent Number of Parameters: 4.74 
Residual Standard Error: 0.4172 </code></pre>
</div>
</div>
<p>Let’s look at the consequence of the span parameter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>loess.spans <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, s){</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  nobs <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  xs <span class="ot">&lt;-</span> <span class="fu">sort</span>(x, <span class="at">index.return =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> xs<span class="sc">$</span>x</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> y[xs<span class="sc">$</span>ix]</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  lo <span class="ot">&lt;-</span> <span class="fu">loess</span>(y <span class="sc">~</span> x, <span class="at">span =</span> s)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">Sepal.Length =</span> x, <span class="at">Sepal.Width =</span> lo<span class="sc">$</span>fitted, <span class="at">span =</span> s)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>( <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.2</span> ),</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.3</span> ),</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.4</span> ),</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.5</span> ),</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.6</span> ),</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.7</span> ),</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.8</span> ) )  <span class="sc">|&gt;</span> </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">span =</span> <span class="fu">factor</span>( span, <span class="at">ordered=</span><span class="cn">TRUE</span> )) <span class="sc">|&gt;</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(Sepal.Length, Sepal.Width) ) <span class="sc">+</span> </span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="at">data =</span> iris, ) <span class="sc">+</span> </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>( <span class="fu">aes</span>(<span class="at">color =</span> span ), <span class="at">lwd=</span><span class="dv">1</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>One method suggested to figure out what an optimal value of <code>span</code> would be is based upon a generalized cross validation (GCV) approach.</p>
<p><span class="math display">\[
s = \frac{ \frac{1}{N} \sum_{i=1}^N (y_i - \hat{y}_{i,s})^2 }{ (1 - \frac{v_s}{n} )^2 }
\]</span></p>
<p>where <span class="math inline">\(v_s = \sum_{i=1}^N h_{ii,s}\)</span> is the trace of the idempotent <span class="math inline">\(\mathbf{H}\)</span> <a href="https://www.sciencedirect.com/topics/mathematics/hat-matrix">Hat Matrix</a>.</p>
<p>Here is a function that does this for the general loess model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>loess.gcv <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y){</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  nobs <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  xs <span class="ot">&lt;-</span> <span class="fu">sort</span>(x, <span class="at">index.return =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> xs<span class="sc">$</span>x</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> y[xs<span class="sc">$</span>ix]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  tune.loess <span class="ot">&lt;-</span> <span class="cf">function</span>(s){</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    lo <span class="ot">&lt;-</span> <span class="fu">loess</span>(y <span class="sc">~</span> x, <span class="at">span =</span> s)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>((lo<span class="sc">$</span>fitted <span class="sc">-</span> y)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> lo<span class="sc">$</span>trace.hat<span class="sc">/</span>nobs)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  os <span class="ot">&lt;-</span> <span class="fu">optimize</span>(tune.loess, <span class="at">interval =</span> <span class="fu">c</span>(.<span class="dv">01</span>, <span class="dv">99</span>))<span class="sc">$</span>minimum</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  lo <span class="ot">&lt;-</span> <span class="fu">loess</span>(y <span class="sc">~</span> x, <span class="at">span =</span> os)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">Sepal.Length =</span> x, <span class="at">Sepal.Width =</span> lo<span class="sc">$</span>fitted, <span class="at">span =</span> os)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>( <span class="fu">loess.gcv</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width ),</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>       <span class="fu">loess.spans</span>( iris<span class="sc">$</span>Sepal.Length, iris<span class="sc">$</span>Sepal.Width, <span class="at">s =</span> <span class="fl">0.75</span> ) ) <span class="sc">|&gt;</span> </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">span =</span> <span class="fu">factor</span>(<span class="fu">round</span>(span,<span class="at">digits =</span> <span class="dv">2</span>))) <span class="sc">|&gt;</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(Sepal.Length, Sepal.Width, <span class="at">color=</span>span) ) <span class="sc">+</span> </span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="other-regression-approaches" class="level2">
<h2 class="anchored" data-anchor-id="other-regression-approaches">Other Regression Approaches</h2>
<p>There are several additional approaches including Kernel Regression (e.g., <a href="https://bookdown.org/egarpor/PM-UC3M/npreg-kre.html">Nadaraya &amp; Watson’s Kernel Smoother</a>) and Local Averaging (e.g., <a href="http://fmwww.bc.edu/repec/bocode/s/supsmooth_doc.pdf">Friedman’s Super Smoother</a>). If you need to perform a regression approach, please explore the benefits and challenges with these alternative methods before deciding on which one to use.</p>
<section id="mann-whitney-test-for-the-equivallence-of-two-means" class="level3">
<h3 class="anchored" data-anchor-id="mann-whitney-test-for-the-equivallence-of-two-means">Mann-Whitney Test For the Equivallence of Two Means</h3>
<p>So, this is an extension of the <code>t-test</code> for the equivalence of the mean values of two data sets (e.g., <span class="math inline">\(H_O: \bar{x} = \bar{y}\)</span>). This assume that two sets of data are independently sampled and tests for the equality of the samples based upon ranks of the data in each set.</p>
<section id="assumptions-1" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-1">Assumptions</h4>
<p>This approach has the following assumptions:</p>
<ol type="1">
<li>Both sets of data are random samples from their respective population.<br>
</li>
<li>Each of the populations are similarly independent.</li>
<li>The measurement scale for each variable is at least ordinal (e.g., you can put them in order).</li>
</ol>
<p>For this test, I’m just going to use the <em>Motor Trends</em> car data we’ve seen before and look at the mileage of cars that have a manual vs an automatic transmission. Here is the distribution of the data in a density plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( <span class="at">Transmission =</span> am, <span class="at">MPG =</span> mpg ) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">Transmission =</span> <span class="fu">as.factor</span>( Transmission ) ) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">Transmission =</span> <span class="fu">fct_recode</span>( Transmission, <span class="st">"Automatic"</span><span class="ot">=</span><span class="st">"0"</span>, <span class="st">"Manual"</span><span class="ot">=</span><span class="st">"1"</span>)) <span class="ot">-&gt;</span> data</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(Transmission, MPG) )  <span class="sc">+</span> </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>( <span class="at">notch=</span><span class="cn">TRUE</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Notch went outside hinges
ℹ Do you want `notch = FALSE`?</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To test this, we use the Wilcoxon Rank Sum test. The signature of this test is:</p>
<p><img src="media/Wilcoxon_signature.png" class="img-fluid"></p>
<p>This will take the full set of data, assign them ranked values, and then determine if the ranked values are randomly distributed between the two groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>( MPG <span class="sc">~</span> Transmission, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fit </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  MPG by Transmission
W = 42, p-value = 0.001871
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>As for other analyses, the object returned has a number of elements that may be helpful in writing about the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "statistic"   "parameter"   "p.value"     "null.value"  "alternative"
[6] "method"      "data.name"  </code></pre>
</div>
</div>
</section>
</section>
<section id="kruskal-wallis-test-for-equivallence-of-several-means" class="level3">
<h3 class="anchored" data-anchor-id="kruskal-wallis-test-for-equivallence-of-several-means">Kruskal-Wallis Test for Equivallence of Several Means</h3>
<p>The Kruskal-Wallis test is an extension on the Wilcoxon test in the same way that the <code>aov()</code> is an extension of the <code>t-test()</code>. The approach is again based upon ranks. Here is an example data set we’ve used once before based on air quality measured across five different months.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( Month, Ozone ) <span class="sc">|&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">Month =</span> <span class="fu">factor</span>( Month ) ) <span class="sc">|&gt;</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">Month =</span> <span class="fu">fct_recode</span>(Month, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">May=</span><span class="st">"5"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Jun=</span><span class="st">"6"</span>,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Jul=</span><span class="st">"7"</span>,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Aug=</span><span class="st">"8"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Sep=</span><span class="st">"9"</span> )) <span class="sc">|&gt;</span> </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( <span class="sc">!</span><span class="fu">is.na</span>( Ozone )) <span class="ot">-&gt;</span> data </span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( data, <span class="fu">aes</span>(Month, Ozone) ) <span class="sc">+</span> </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">notch=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Notch went outside hinges
ℹ Do you want `notch = FALSE`?</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="counting_stats_narrative_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To test for the equality of ozone across months, we use <code>kruskal.test()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>( Ozone <span class="sc">~</span> Month, <span class="at">data=</span>data )</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>fit </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Ozone by Month
Kruskal-Wallis chi-squared = 29.267, df = 4, p-value = 6.901e-06</code></pre>
</div>
</div>
<p>And again, the object returned has the relevant parameters for inclusion in the text of your manuscript.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "statistic" "parameter" "p.value"   "method"    "data.name"</code></pre>
</div>
</div>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>These methods should get you going for pure counting statistics (<span class="math inline">\(\Chi^2\)</span>) or for replacements to parametric approaches when you find that your data do not conform to their expectations. There is a whole universe of non-parametric approaches and extensions to the methods I highlight here and I encourage you to explore these methods in the future if you have an odd set of data that needs to yield proper insights.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Cochran, W.G. (1952) The <span class="math inline">\(\Chi^2\)</span> test of goodness of fit. <em>Annals of Mathematical Statistics</em>, 23, 315-345.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>