<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Text Based Data – ENVS 543: Data Literacy (2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/wordcloud2-0.0.1/wordcloud.css" rel="stylesheet">
<script src="site_libs/wordcloud2-0.0.1/wordcloud2-all.js"></script>
<script src="site_libs/wordcloud2-0.0.1/hover.js"></script>
<script src="site_libs/wordcloud2-binding-0.2.1/wordcloud2.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ENVS 543: Data Literacy (2024)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-basics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Basics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-basics">    
        <li class="dropdown-header">markdown_narrative.qmd</li>
        <li class="dropdown-header">basic_data_narrative.qmd</li>
        <li class="dropdown-header">containers_narrative.qmd</li>
        <li>
    <a class="dropdown-item" href="./tidyverse_narrative.html">
 <span class="dropdown-text">Tidyverse</span></a>
  </li>  
        <li class="dropdown-header">functions_narrative.qmd</li>
        <li>
    <a class="dropdown-item" href="./text_narrative.html">
 <span class="dropdown-text">Text Based Data</span></a>
  </li>  
        <li class="dropdown-header">factors_narrative.qmd</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-graphics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Graphics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-graphics">    
        <li>
    <a class="dropdown-item" href="./classic_graphics_narrative.html">
 <span class="dropdown-text">Basic R Graphics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ggplot_narrative.html">
 <span class="dropdown-text"><code>ggplot2</code> Graphics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-spatial" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Spatial</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-spatial">    
        <li>
    <a class="dropdown-item" href="./points_narrative.html">
 <span class="dropdown-text">Spatial Point Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./raster_narrative.html">
 <span class="dropdown-text">Raster Data Narrative</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analyses" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Analyses</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analyses">    
        <li>
    <a class="dropdown-item" href="./correlation_narrative.html">
 <span class="dropdown-text">Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression_narrative.html">
 <span class="dropdown-text">Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aov_narrative.html">
 <span class="dropdown-text">Analysis of Variance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./counting_stats_narrative.html">
 <span class="dropdown-text">Non-Parametric &amp; Counting Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#topic" id="toc-topic" class="nav-link active" data-scroll-target="#topic">Topic</a></li>
  <li><a href="#data-types" id="toc-data-types" class="nav-link" data-scroll-target="#data-types">Data Types</a></li>
  <li><a href="#the-stringr-library" id="toc-the-stringr-library" class="nav-link" data-scroll-target="#the-stringr-library">The <code>stringr</code> Library</a></li>
  <li><a href="#the-verbs" id="toc-the-verbs" class="nav-link" data-scroll-target="#the-verbs">The ’Verbs”</a>
  <ul class="collapse">
  <li><a href="#creating" id="toc-creating" class="nav-link" data-scroll-target="#creating">Creating</a></li>
  <li><a href="#finding" id="toc-finding" class="nav-link" data-scroll-target="#finding">Finding</a></li>
  <li><a href="#deleting" id="toc-deleting" class="nav-link" data-scroll-target="#deleting">Deleting</a></li>
  <li><a href="#replacing" id="toc-replacing" class="nav-link" data-scroll-target="#replacing">Replacing</a></li>
  <li><a href="#manipulating" id="toc-manipulating" class="nav-link" data-scroll-target="#manipulating">Manipulating</a></li>
  </ul></li>
  <li><a href="#a-practical-example-text-parsing" id="toc-a-practical-example-text-parsing" class="nav-link" data-scroll-target="#a-practical-example-text-parsing">A Practical Example: Text Parsing</a>
  <ul class="collapse">
  <li><a href="#regular-expressions" id="toc-regular-expressions" class="nav-link" data-scroll-target="#regular-expressions">Regular Expressions</a>
  <ul class="collapse">
  <li><a href="#matching" id="toc-matching" class="nav-link" data-scroll-target="#matching">Matching</a></li>
  <li><a href="#combining-matches" id="toc-combining-matches" class="nav-link" data-scroll-target="#combining-matches">Combining Matches</a></li>
  <li><a href="#positional-matching" id="toc-positional-matching" class="nav-link" data-scroll-target="#positional-matching">Positional Matching</a></li>
  <li><a href="#putting-it-together" id="toc-putting-it-together" class="nav-link" data-scroll-target="#putting-it-together">Putting it Together</a></li>
  </ul></li>
  <li><a href="#extra-credit" id="toc-extra-credit" class="nav-link" data-scroll-target="#extra-credit">Extra Credit</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Text Based Data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="media/bruno-martins-OhJmwB4XWLE-unsplash.jpg" class="img-fluid"></p>
<section id="topic" class="level2">
<h2 class="anchored" data-anchor-id="topic">Topic</h2>
<p>This quick section will focus on the text—or, more aptly, <code>character</code>—data type. We commonly run across this as narrative or designations such as site names, locations, other bits of information that we need to</p>
</section>
<section id="data-types" class="level2">
<h2 class="anchored" data-anchor-id="data-types">Data Types</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">"Rodney"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="st">'Dyer'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You could use either single or double quotes to define a character type <em>de novo</em>—both work just fine. Having two of them is really helpful when you want to use one of the quote symbols inside the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="st">'Bob Marley once said, "It is a foolish dog that barks at a passing bird"'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Marley once said, \"It is a foolish dog that barks at a passing bird\""</code></pre>
</div>
</div>
<p>But notice that when you print it out to the terminal (or in the output to your Quarto chunck), it uses the <code>backslash-double quote</code> format. It also show up if you use <code>print</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Marley once said, \"It is a foolish dog that barks at a passing bird\""</code></pre>
</div>
</div>
<p>But not when you <code>cat</code> it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bob Marley once said, "It is a foolish dog that barks at a passing bird"</code></pre>
</div>
</div>
<p>This is called <em>escaping</em> a special character. And it is a valid way to embed a quoting character into a sequence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="st">"</span><span class="sc">\"</span><span class="st">Learning R is Fun,</span><span class="sc">\"</span><span class="st"> said Rodney."</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(w)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>"Learning R is Fun," said Rodney.</code></pre>
</div>
</div>
<p>There are other special characters that you will run across such as:</p>
<ul>
<li>The <code>Tab</code> character, <code>\t</code></li>
<li>The <code>New Line</code> character <code>\n</code></li>
<li>The <code>Return</code> character <code>\r</code>. This is becoming obsolete, in the “olden days” it was used with new line when we were making a transition from the manual typewriter where if you think about the action of using a typewriter, you need to advance a line AND return the carrage—the part that makes the letters on the paper—to the beginning of the line. That is why you sometimes see CR for on the return key. Windows used this convention and you may run across it still form peole who use that platform as <code>\r\n</code>. Mostly it is just yet another annoyance from some Windows software.</li>
</ul>
<p>To see more, visit <code>?"'"</code> in R.</p>
</section>
<section id="the-stringr-library" class="level2">
<h2 class="anchored" data-anchor-id="the-stringr-library">The <code>stringr</code> Library</h2>
<p>Another joy from the <code>tidyverse</code> folks is the <code>stringr</code> library that has made things a bit easier in handling string data. As usual, there is a cheatsheet linked in the assets on this topic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( tidyverse )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-verbs" class="level2">
<h2 class="anchored" data-anchor-id="the-verbs">The ’Verbs”</h2>
<p>When dealing with text, there are some basic <code>verbs</code> that we should recognize as fundamental actions that you’ll apply across a wide variety of situations. For text data, these include:</p>
<ul>
<li><code>Creating</code> new/composite text.</li>
<li><code>Finding</code> content inside a string.</li>
<li><code>Deleting</code> content within a string</li>
<li><code>Replacing</code> content in a string with some new character value.</li>
<li><code>Manipulating</code> content in a string.</li>
</ul>
<section id="creating" class="level3">
<h3 class="anchored" data-anchor-id="creating">Creating</h3>
<p>We’ve already seen how to create a single string, here is how we can smush (yes that is a technical term) together several kinds of data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>( <span class="st">"This"</span>,<span class="st">"is"</span>,<span class="st">"fun"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "This is fun"</code></pre>
</div>
</div>
<p>You can also mix-and-match different data types, as long as they can be coerced into a string type (which all data types can).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>num <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"It is"</span>, <span class="cn">TRUE</span>, <span class="st">"that my favorite number is"</span>, num, <span class="st">"."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "It is TRUE that my favorite number is 42 ."</code></pre>
</div>
</div>
<p>When we work with character data, we need to realize that from the context of indexing, such as when we use a vector or <code>data.frame</code>, the sequence of characters is all one object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Even if it is made up of several characters. If we are interested subsequences within the string, we need to ask more specifically about the string length, not the variable length.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_length</span>( z )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 72</code></pre>
</div>
</div>
<p>There are times when we need to paste more than a couple of individual items together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>( a )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>( a, <span class="at">sep=</span><span class="st">", "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>( a, <span class="at">collapse=</span><span class="st">", "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"</code></pre>
</div>
</div>
<p>as separate columns</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">12</span>, <span class="dv">1</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>( a,b,c, <span class="at">sep =</span> <span class="st">"-"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "1-A-12.7912652771503"  "2-B-11.8937010477833"  "3-C-11.3898231358371" 
 [4] "4-D-11.4967532001624"  "5-E-13.2612608777438"  "6-F-10.3265825835173" 
 [7] "7-G-11.1325734875453"  "8-H-11.8791143979628"  "9-I-11.5220014537577" 
[10] "10-J-12.3076359305748"</code></pre>
</div>
</div>
<p>A <code>stringr</code> version is also available—with fewer keystrokes!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>( a, <span class="at">collapse=</span><span class="st">", "</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"</code></pre>
</div>
</div>
<p>and</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>( a,b,c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "1A12.7912652771503"  "2B11.8937010477833"  "3C11.3898231358371" 
 [4] "4D11.4967532001624"  "5E13.2612608777438"  "6F10.3265825835173" 
 [7] "7G11.1325734875453"  "8H11.8791143979628"  "9I11.5220014537577" 
[10] "10J12.3076359305748"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>( a,b,c, <span class="at">sep=</span><span class="st">"-"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "1-A-12.7912652771503"  "2-B-11.8937010477833"  "3-C-11.3898231358371" 
 [4] "4-D-11.4967532001624"  "5-E-13.2612608777438"  "6-F-10.3265825835173" 
 [7] "7-G-11.1325734875453"  "8-H-11.8791143979628"  "9-I-11.5220014537577" 
[10] "10-J-12.3076359305748"</code></pre>
</div>
</div>
</section>
<section id="finding" class="level3">
<h3 class="anchored" data-anchor-id="finding">Finding</h3>
<p>Finding text may be done in a few ways.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bob Marley once said, "It is a foolish dog that barks at a passing bird"</code></pre>
</div>
</div>
<p>We can ask if:</p>
<ol type="1">
<li>A particular sequence of characters exist in the string (<code>TRUE/FALSE</code>).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>(z, <span class="st">"Marley"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>(z, <span class="st">"marley"</span>) <span class="co"># case sensitive</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>We can ask for the number of times a sequences shows up in a string.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_count</span>(z, <span class="st">"a"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>We can ask where the first occurance of a subsequence of characters starts at:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_locate</span>( z, <span class="st">"dog"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     start end
[1,]    40  42</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We can find all occurences of a substring.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_locate_all</span>( z, <span class="st">"a"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
     start end
[1,]     6   6
[2,]    18  18
[3,]    30  30
[4,]    46  46
[5,]    50  50
[6,]    55  55
[7,]    58  58
[8,]    61  61</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>If we know the location of a substring, you can extract it. Here I use the negative for the second index, which is treated as “second from the end” of the string.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(z, <span class="dv">24</span>, <span class="sc">-</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "It is a foolish dog that barks at a passing bird"</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>If we have several character objects in a vector, we can find the subset that contains a specific sequence.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>character_vec <span class="ot">&lt;-</span> <span class="fu">c</span>(w,x,y,z)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>character_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\"Learning R is Fun,\" said Rodney."                                       
[2] "Rodney"                                                                    
[3] "Dyer"                                                                      
[4] "Bob Marley once said, \"It is a foolish dog that barks at a passing bird\""</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>( character_vec, <span class="st">"r"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
</div>
<p>However, it is case sensitive</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>( character_vec, <span class="st">"R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE FALSE</code></pre>
</div>
</div>
</section>
<section id="deleting" class="level3">
<h3 class="anchored" data-anchor-id="deleting">Deleting</h3>
<p>This is an easy one, if we want to remove one (the first occurence of) an item,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_remove</span>(z,<span class="st">"dog"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Marley once said, \"It is a foolish  that barks at a passing bird\""</code></pre>
</div>
</div>
<p>Or all of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_remove_all</span>(z, <span class="st">"a"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Mrley once sid, \"It is  foolish dog tht brks t  pssing bird\""</code></pre>
</div>
</div>
<p>We can also remove compoennts by truncation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_trunc</span>( character_vec , <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\"Learning R is Fu..." "Rodney"                "Dyer"                 
[4] "Bob Marley once s..." </code></pre>
</div>
</div>
</section>
<section id="replacing" class="level3">
<h3 class="anchored" data-anchor-id="replacing">Replacing</h3>
<p>There are times when we are wanting to take some component within a string and replace it with another one—independent of the location of the item to be replaced within the string.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>( <span class="fu">str_replace</span>(z, <span class="st">"Bob Marley"</span>, <span class="st">"Rodney"</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rodney once said, "It is a foolish dog that barks at a passing bird"</code></pre>
</div>
</div>
<p>If we do know the location (character location) and size (<code>str_length</code>) of what we are replacing, then we can use those numerical values direction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(z, <span class="dv">1</span>, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Marley"</code></pre>
</div>
</div>
</section>
<section id="manipulating" class="level3">
<h3 class="anchored" data-anchor-id="manipulating">Manipulating</h3>
<ol type="1">
<li>Making the string all lower case.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_to_lower</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "bob marley once said, \"it is a foolish dog that barks at a passing bird\""</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Making it all uppercase.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_to_upper</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BOB MARLEY ONCE SAID, \"IT IS A FOOLISH DOG THAT BARKS AT A PASSING BIRD\""</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Creating <code>Title Case</code> text.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_to_title</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bob Marley Once Said, \"It Is A Foolish Dog That Barks At A Passing Bird\""</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Capitalizing it as if it were a sentence.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_to_sentence</span>( <span class="st">"this is getting a bit old, isn't it?"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "This is getting a bit old, isn't it?"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">str_to_sentence</span>(<span class="st">"rodney exclaimed, </span><span class="sc">\"</span><span class="st">but it doesn't know about internal quoted sentence fragments!</span><span class="sc">\"</span><span class="st"> and then sat down."</span>) </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(tmp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rodney exclaimed, "but it doesn't know about internal quoted sentence fragments!" And then sat down.</code></pre>
</div>
</div>
</section>
</section>
<section id="a-practical-example-text-parsing" class="level1">
<h1>A Practical Example: Text Parsing</h1>
<div class="callout callout-style-default callout-important callout-titled" title="Practical Problem">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practical Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are working on curriculum at VCU and need to generate a <code>data.frame</code> of courses that have a columns for <code>Program</code>, <code>Course Number</code>, <code>Course Title</code>, and <code>Credit Hours</code>.</p>
<p>The raw data you have is the university bulletin.</p>
</div>
</div>
<section id="regular-expressions" class="level2">
<h2 class="anchored" data-anchor-id="regular-expressions">Regular Expressions</h2>
<p>A regular expression, or <em>regex</em> is a concise language used for detecting and describing patterns found in language. An entire course could be taught on the use of <em>regex</em> but here we’ll only spend enough time on it so that you know some kind of magic exists in the universe and can explore it if you need to in the future.</p>
<p>For this example, I’m going to use some text data that I have been playing with regarding curriculum development.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( readr )</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/DyerlabTeaching/Textual-Data/refs/heads/main/data/ENVSclasses.txt?token=GHSAT0AAAAAACWO27UIA46V72P7DBZEP5EKZYZFFXQ"</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">read_lines</span>( url ) <span class="ot">-&gt;</span> envs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This goes out and grabs the data, and reads it in as a vector of type character.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( envs )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>If we take a look at it, we can see these are the listings for the undergraduate courses in Environmental Studies at <a href="https://vcu.edu">VCU</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(envs,<span class="dv">17</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ENVS 101. Introduction to Environmental Studies I. 3 Hours."                
 [2] "Semester course; 3 lecture hours. 3 credits. Enrollment is restricted to"   
 [3] "environmental studies majors. Study of contemporary issues related to"      
 [4] "environmental studies including sustainability, biological conservation,"   
 [5] "global change and an overview of the core earth systems."                   
 [6] "ENVS 102. Introduction to Environmental Studies II. 3 Hours."               
 [7] "Semester course; 3 lecture hours. 3 credits. Prerequisite: ENVS 101 or"     
 [8] "permission of instructor. Enrollment is restricted to environmental studies"
 [9] "majors. Studies of contemporary issues related to government policy and"    
[10] "environmental issues at local to international scales."                     
[11] "886 Undergraduate courses"                                                  
[12] "ENVS 105. Physical Geology. 3 Hours."                                       
[13] "Semester course; 3 lecture hours. 3 credits. A descriptive approach to"     
[14] "physical geology dealing with the history and structure of the earth,"      
[15] "catastrophic events and geology as it relates to the contemporary"          
[16] "environment. An optional laboratory, ENVZ 105, may be taken with this"      
[17] "course."                                                                    </code></pre>
</div>
</div>
<p>There are a couple of things to notice:</p>
<ol type="1">
<li>The lines are short and the entry for each course is spread across several lines.<br>
</li>
<li>Each course has a 4-letter code, a 3-digit number, a title, and then ends with the number of hours for the class.</li>
<li>There are five lines necessary to describe ENVS 101 but six for ENVS 105.</li>
<li>Line 11 appears to be a page number and page heading and not part of any course description.</li>
</ol>
<p>Let’s say we wanted to extract some information about the course number, name, and number of hours from these data. This subset of data only has 262 line of text but if we were looking at all the courses at VCU, we would be faced with 25,945 lines of text! It could be done by hand but… that does not scale too well and I’ve got a lot better things to do than spend a year working on this simple task.</p>
<section id="matching" class="level3">
<h3 class="anchored" data-anchor-id="matching">Matching</h3>
<p>Let’s start by matching. Let’s look at what we did above and see if there are any tools we can use.</p>
<p>We do know that <code>str_detect()</code> will give us a <code>TRUE/FALSE</code> for any match. Let’s try that and take a look at the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">str_detect</span>(envs,<span class="st">"ENVS"</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>( envs[idx] )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENVS 101. Introduction to Environmental Studies I. 3 Hours."           
[2] "ENVS 102. Introduction to Environmental Studies II. 3 Hours."          
[3] "Semester course; 3 lecture hours. 3 credits. Prerequisite: ENVS 101 or"
[4] "ENVS 105. Physical Geology. 3 Hours."                                  
[5] "ENVS 201. Earth System Science. 3 Hours."                              
[6] "ENVS 222. Electronic Portfolios. 1 Hour."                              </code></pre>
</div>
</div>
<p>OK, except that line 3 isn’t a title line, it just has an <code>ENVS</code> in it.</p>
<p>Moveover, it also assumes that we are going to only be using <code>ENVS</code> but if we look at the end of the data set, we see that the lab courses in Environmental Studies are encoded as <code>ENVZ</code> and these will be totally ignored. Moreover, we would need to know, <em>a priori</em>, what all the program codes were before we started if we were going to take this approach.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>( envs )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Laboratory exercises coordinated with ENVS 335 lectures."                 
[2] "ENVZ 401. Meteorology and Climatology Laboratory. 1 Hour."                
[3] "Semester course; 3 laboratory hours. 1 credit. Pre- or corequisite:"      
[4] "ENVS 401. A series of laboratory and field experiments designed to"       
[5] "quantify the elements of weather and climate and to interpret their local"
[6] "temporal and spatial variations."                                         </code></pre>
</div>
</div>
<p>Using <em>regex</em> we can define a character <strong>pattern</strong> to look for. Let’s start by just taking the first line of text and using that to learn about pattern matching.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>envs101 <span class="ot">&lt;-</span> envs[<span class="dv">1</span>]</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>envs101</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENVS 101. Introduction to Environmental Studies I. 3 Hours."</code></pre>
</div>
</div>
<p>The <code>stringr</code> library has a helper function that allows us to see what parts of a string are being matched by a specific pattern. This function is <code>str_view()</code> and it colors and puts into angle brackets, the part that is matched.</p>
<p>So, looking for the characters <code>ENVS</code> looks like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(envs101,<span class="st">"ENVS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS&gt; 101. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<p>and looking for <code>101</code> yields.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"101"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS &lt;101&gt;. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<p>If ther is no match, nothing is returned:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"Rodney"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and if many things are matched, it will highlight each of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"o"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS 101. Intr&lt;o&gt;ducti&lt;o&gt;n t&lt;o&gt; Envir&lt;o&gt;nmental Studies I. 3 H&lt;o&gt;urs.</code></pre>
</div>
</div>
<p>So, let’s get more general and look for patterns. These patterns are encoded using square brackets.</p>
<ol type="1">
<li>Matching on any digit, which is defined as <code>[:digit:]</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:digit:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS &lt;1&gt;&lt;0&gt;&lt;1&gt;. Introduction to Environmental Studies I. &lt;3&gt; Hours.</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Matching any non-numeric character, <code>[:alpha:]</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:alpha:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;E&gt;&lt;N&gt;&lt;V&gt;&lt;S&gt; 101. &lt;I&gt;&lt;n&gt;&lt;t&gt;&lt;r&gt;&lt;o&gt;&lt;d&gt;&lt;u&gt;&lt;c&gt;&lt;t&gt;&lt;i&gt;&lt;o&gt;&lt;n&gt; &lt;t&gt;&lt;o&gt; &lt;E&gt;&lt;n&gt;&lt;v&gt;&lt;i&gt;&lt;r&gt;&lt;o&gt;&lt;n&gt;&lt;m&gt;&lt;e&gt;&lt;n&gt;&lt;t&gt;&lt;a&gt;&lt;l&gt; &lt;S&gt;&lt;t&gt;&lt;u&gt;&lt;d&gt;&lt;i&gt;&lt;e&gt;&lt;s&gt; &lt;I&gt;. 3 &lt;H&gt;&lt;o&gt;&lt;u&gt;&lt;r&gt;&lt;s&gt;.</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Matching punctuation, <code>[:punct:]</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:punct:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS 101&lt;.&gt; Introduction to Environmental Studies I&lt;.&gt; 3 Hours&lt;.&gt;</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We can also specify the case of the punctuation.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:lower:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS 101. I&lt;n&gt;&lt;t&gt;&lt;r&gt;&lt;o&gt;&lt;d&gt;&lt;u&gt;&lt;c&gt;&lt;t&gt;&lt;i&gt;&lt;o&gt;&lt;n&gt; &lt;t&gt;&lt;o&gt; E&lt;n&gt;&lt;v&gt;&lt;i&gt;&lt;r&gt;&lt;o&gt;&lt;n&gt;&lt;m&gt;&lt;e&gt;&lt;n&gt;&lt;t&gt;&lt;a&gt;&lt;l&gt; S&lt;t&gt;&lt;u&gt;&lt;d&gt;&lt;i&gt;&lt;e&gt;&lt;s&gt; I. 3 H&lt;o&gt;&lt;u&gt;&lt;r&gt;&lt;s&gt;.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:upper:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;E&gt;&lt;N&gt;&lt;V&gt;&lt;S&gt; 101. &lt;I&gt;ntroduction to &lt;E&gt;nvironmental &lt;S&gt;tudies &lt;I&gt;. 3 &lt;H&gt;ours.</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Or even spaces</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:space:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS&lt; &gt;101.&lt; &gt;Introduction&lt; &gt;to&lt; &gt;Environmental&lt; &gt;Studies&lt; &gt;I.&lt; &gt;3&lt; &gt;Hours.</code></pre>
</div>
</div>
</section>
<section id="combining-matches" class="level3">
<h3 class="anchored" data-anchor-id="combining-matches">Combining Matches</h3>
<p>That is helpful in some cases. But now we can start combining these things.</p>
<ol type="1">
<li>Let’s mix a pattern and a fixed set of characters.<br>
</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:digit:] Hours"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS 101. Introduction to Environmental Studies I. &lt;3 Hours&gt;.</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>How about multiple patterns.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:upper:][:space:][:digit:]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENV&lt;S 1&gt;01. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Or multiples of the same pattern. To have the exact number of items, use a single number enclosed in curly brackets right after ther pattern. Here we are matching 4-upper case digits.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(envs101, <span class="st">"[:upper:]{4}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS&gt; 101. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<p>We could also match those followed by a space and three numbers</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:upper:]{4}[:space:][:digit:]{3}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS 101&gt;. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>We can generalize this a bit by asking for “zero or one” or “zero or more”—IMHO this is a terrible thing to match as a single thing.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:punct:]?"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;&gt;E&lt;&gt;N&lt;&gt;V&lt;&gt;S&lt;&gt; &lt;&gt;1&lt;&gt;0&lt;&gt;1&lt;.&gt;&lt;&gt; &lt;&gt;I&lt;&gt;n&lt;&gt;t&lt;&gt;r&lt;&gt;o&lt;&gt;d&lt;&gt;u&lt;&gt;c&lt;&gt;t&lt;&gt;i&lt;&gt;o&lt;&gt;n&lt;&gt; &lt;&gt;t&lt;&gt;o&lt;&gt; &lt;&gt;E&lt;&gt;n&lt;&gt;v&lt;&gt;i&lt;&gt;r&lt;&gt;o&lt;&gt;n&lt;&gt;m&lt;&gt;e&lt;&gt;n&lt;&gt;t&lt;&gt;a&lt;&gt;l&lt;&gt; &lt;&gt;S&lt;&gt;t&lt;&gt;u&lt;&gt;d&lt;&gt;i&lt;&gt;e&lt;&gt;s&lt;&gt; &lt;&gt;I&lt;.&gt;&lt;&gt; &lt;&gt;3&lt;&gt; &lt;&gt;H&lt;&gt;o&lt;&gt;u&lt;&gt;r&lt;&gt;s&lt;.&gt;&lt;&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:punct:]*"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;&gt;E&lt;&gt;N&lt;&gt;V&lt;&gt;S&lt;&gt; &lt;&gt;1&lt;&gt;0&lt;&gt;1&lt;.&gt;&lt;&gt; &lt;&gt;I&lt;&gt;n&lt;&gt;t&lt;&gt;r&lt;&gt;o&lt;&gt;d&lt;&gt;u&lt;&gt;c&lt;&gt;t&lt;&gt;i&lt;&gt;o&lt;&gt;n&lt;&gt; &lt;&gt;t&lt;&gt;o&lt;&gt; &lt;&gt;E&lt;&gt;n&lt;&gt;v&lt;&gt;i&lt;&gt;r&lt;&gt;o&lt;&gt;n&lt;&gt;m&lt;&gt;e&lt;&gt;n&lt;&gt;t&lt;&gt;a&lt;&gt;l&lt;&gt; &lt;&gt;S&lt;&gt;t&lt;&gt;u&lt;&gt;d&lt;&gt;i&lt;&gt;e&lt;&gt;s&lt;&gt; &lt;&gt;I&lt;.&gt;&lt;&gt; &lt;&gt;3&lt;&gt; &lt;&gt;H&lt;&gt;o&lt;&gt;u&lt;&gt;r&lt;&gt;s&lt;.&gt;&lt;&gt;</code></pre>
</div>
</div>
<p>But for our purposes, we can ask for “one or more” by appending a plus sign.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:digit:]+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ ENVS &lt;101&gt;. Introduction to Environmental Studies I. &lt;3&gt; Hours.</code></pre>
</div>
</div>
<p>or match to digits, punctuation, or letters (one or more) using the shorthand <code>.+</code> notation. It is the period that matches anything and the plus that does one or more of them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">".+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS 101. Introduction to Environmental Studies I. 3 Hours.&gt;</code></pre>
</div>
</div>
<p>This becomes helpful a bit later when we are trying to anchor the course designation (e.g., ENVS 101) at the start, ONE OR MORE THING IN THE MIDDLE, and then the end of the line with the number of hours (e.g., 3 Hours.)</p>
</section>
<section id="positional-matching" class="level3">
<h3 class="anchored" data-anchor-id="positional-matching">Positional Matching</h3>
<p>Where the items is in the string may be of importance to us. For example, consider another line in the data that specifies ENVS101 as a prerequisite. It does not come from a line of text that is the title of the course, it just also happens to match the 4 uppercase letters, space, and three digits pattern.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs[<span class="dv">37</span>], <span class="st">"[:upper:]{4}[:space:][:digit:]{3}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ Semester course; 2 lecture hours. 2 credits. Prerequisites: &lt;ENVS 101&gt;</code></pre>
</div>
</div>
<p>This is where the position in the line may be of interest.</p>
<ol type="1">
<li>To match things that occur at the beginning of the string, we prepend the pattern with the carat symbol.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"^[:upper:]{4}[:space:][:digit:]{3}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS 101&gt;. Introduction to Environmental Studies I. 3 Hours.</code></pre>
</div>
</div>
<p>This matches our first line but not a line where this pattern does not occur in the beginning of the string.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs[<span class="dv">37</span>], <span class="st">"^[:upper:]{4}[:space:][:digit:]{3}"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>For the end of the string, we use the dollar sign to anchor it to the end.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs[<span class="dv">37</span>], <span class="st">"[:upper:]{4}[:space:][:digit:]{3}$"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ Semester course; 2 lecture hours. 2 credits. Prerequisites: &lt;ENVS 101&gt;</code></pre>
</div>
</div>
<p>which is not in the envs101 string</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"[:upper:]{4}[:space:][:digit:]{3}$"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="putting-it-together" class="level3">
<h3 class="anchored" data-anchor-id="putting-it-together">Putting it Together</h3>
<p>So, now let’s pull this all together and see if we can match: 1. The course designation at the start of the line. 2. The title 3. The end of the line with the number of hours.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, <span class="st">"^[:upper:]{4} [:digit:]{3}.*[:digit:] Hours.$"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS 101. Introduction to Environmental Studies I. 3 Hours.&gt;</code></pre>
</div>
</div>
<p>So, there is one little extension—and this a common theme we’ve run across—and that has to do with the fact that programmers are a bit lazy. You can subsititue, the square-bracket-colon-word-colon-square-bracket for the following:</p>
<ul>
<li><code>[0-9]</code> is shorthand for <code>[:digits:]</code>.</li>
<li><code>[a-z]</code> is shorthand for <code>[:lower:]</code>.<br>
</li>
<li><code>[A-Z]</code> is shorthand for <code>[:upper:]</code>.</li>
</ul>
<p>Which means that we can go from</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>pattern <span class="ot">&lt;-</span> <span class="st">"^[:upper:]{4} [:digit:]{3}.*[:digit:] Hours.$"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>to this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>pattern <span class="ot">&lt;-</span> <span class="st">"^[A-Z]{4} [0-9]{3}.+[0-9] Hours.$"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>as our seach pattern.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>( envs101, pattern )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] │ &lt;ENVS 101. Introduction to Environmental Studies I. 3 Hours.&gt;</code></pre>
</div>
</div>
<p>Instead of asking a single line, we need to apply this expressions to each line in the data an return the ones that match. For this, we can use <code>grepl</code>, which returns a <code>TRUE/FALSE</code> on matching. The tricky thing here is that the pattern comes first and the vector second (reverse from what we’ve been using.)</p>
<p>So for our data, we see</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grepl</span>(pattern, envs )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE
 [13] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [49] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
[133] FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
[145] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[157] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[169] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
[181] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[193] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[205] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[217] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
[229] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
[241]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[253] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<p>Which is great as we can use it for extracting the lines of the data that have our information. Let’s use the <code>grepl</code> as indices and grab the titles from <code>envs</code> using it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">grepl</span>( pattern, envs )</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>envs[idx] <span class="ot">-&gt;</span> titles</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>titles</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ENVS 101. Introduction to Environmental Studies I. 3 Hours."     
 [2] "ENVS 102. Introduction to Environmental Studies II. 3 Hours."    
 [3] "ENVS 105. Physical Geology. 3 Hours."                            
 [4] "ENVS 201. Earth System Science. 3 Hours."                        
 [5] "ENVS 260. Outdoor Leadership. 3 Hours."                          
 [6] "ENVS 265. Paths to Environmental Leadership. 2 Hours."           
 [7] "ENVS 291. Special Topics in Environmental Studies. 1-4 Hours."   
 [8] "ENVS 300. Sustainable Societies: James River Basin. 3 Hours."    
 [9] "ENVS 301. Introduction to Meteorology. 3 Hours."                 
[10] "ENVS 310. Introduction to Oceanography. 3 Hours."                
[11] "ENVS 311. Politics of the Environment. 3 Hours."                 
[12] "ENVS 315. Energy and the Environment. 3 Hours."                  
[13] "ENVS 321. Cartography. 3 Hours."                                 
[14] "ENVS 330. Environmental Pollution. 3 Hours."                     
[15] "ENVS 332. Environmental Management. 3 Hours."                    
[16] "ENVS 335. Environmental Geology. 3 Hours."                       
[17] "ENVS 343. Data Literacy. 4 Hours."                               
[18] "ENVS 355. Water. 3 Hours."                                       
[19] "ENVS 360. Outdoor Programming and Event Management. 3 Hours."    
[20] "ENVS 361. Outdoor Team Building and Group Facilitation. 3 Hours."
[21] "ENVS 368. Nature Writing. 3 Hours."                              
[22] "ENVS 370. Applications of Conservation Science. 3 Hours."        
[23] "ENVS 391. Special Topics in Environmental Studies. 1-4 Hours."   
[24] "ENVS 401. Meteorology and Climatology. 3 Hours."                 
[25] "ENVS 411. Oceanography. 3 Hours."                                
[26] "ENVS 421. Environmental Data Visualization. 3 Hours."            
[27] "ENVS 430. Invasive Species Management. 3 Hours."                 
[28] "ENVS 460. Wilderness First Responder. 3 Hours."                  
[29] "ENVS 461. Wilderness Policy and Practice. 3 Hours."              
[30] "ENVS 490. Research Seminar in Environmental Studies. 3 Hours."   
[31] "ENVS 491. Topics in Environmental Studies. 1-4 Hours."           
[32] "ENVS 492. Independent Study. 1-3 Hours."                         
[33] "ENVS 493. Environmental Studies Internship. 1-3 Hours."          
[34] "ENVS 499. Environmental Studies Capstone Experience. 0 Hours."   </code></pre>
</div>
</div>
<p>That looks pretty good! We are almost there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">str_split</span>(titles, <span class="at">pattern=</span><span class="st">"</span><span class="sc">\\</span><span class="st">."</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34  4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]       [,2]                                        [,3]       [,4]
[1,] "ENVS 101" " Introduction to Environmental Studies I"  " 3 Hours" ""  
[2,] "ENVS 102" " Introduction to Environmental Studies II" " 3 Hours" ""  
[3,] "ENVS 105" " Physical Geology"                         " 3 Hours" ""  
[4,] "ENVS 201" " Earth System Science"                     " 3 Hours" ""  
[5,] "ENVS 260" " Outdoor Leadership"                       " 3 Hours" ""  
[6,] "ENVS 265" " Paths to Environmental Leadership"        " 2 Hours" ""  </code></pre>
</div>
</div>
<p>OK, so now we can easily grab these columns and put them into a <code>data.frame</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>program <span class="ot">&lt;-</span> <span class="fu">str_split</span>( raw[,<span class="dv">1</span>], <span class="at">pattern=</span><span class="st">" "</span>, <span class="at">simplify=</span><span class="cn">TRUE</span>)[,<span class="dv">1</span>]</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>program </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS"
[11] "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS"
[21] "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS" "ENVS"
[31] "ENVS" "ENVS" "ENVS" "ENVS"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>code <span class="ot">&lt;-</span> <span class="fu">str_split</span>( raw[,<span class="dv">1</span>], <span class="at">pattern=</span><span class="st">" "</span>, <span class="at">simplify=</span><span class="cn">TRUE</span>)[,<span class="dv">2</span>]</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>code <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>( code )</span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>code </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 101 102 105 201 260 265 291 300 301 310 311 315 321 330 332 335 343 355 360
[20] 361 368 370 391 401 411 421 430 460 461 490 491 492 493 499</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>title <span class="ot">&lt;-</span> raw[,<span class="dv">2</span>]</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>title</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] " Introduction to Environmental Studies I"     
 [2] " Introduction to Environmental Studies II"    
 [3] " Physical Geology"                            
 [4] " Earth System Science"                        
 [5] " Outdoor Leadership"                          
 [6] " Paths to Environmental Leadership"           
 [7] " Special Topics in Environmental Studies"     
 [8] " Sustainable Societies: James River Basin"    
 [9] " Introduction to Meteorology"                 
[10] " Introduction to Oceanography"                
[11] " Politics of the Environment"                 
[12] " Energy and the Environment"                  
[13] " Cartography"                                 
[14] " Environmental Pollution"                     
[15] " Environmental Management"                    
[16] " Environmental Geology"                       
[17] " Data Literacy"                               
[18] " Water"                                       
[19] " Outdoor Programming and Event Management"    
[20] " Outdoor Team Building and Group Facilitation"
[21] " Nature Writing"                              
[22] " Applications of Conservation Science"        
[23] " Special Topics in Environmental Studies"     
[24] " Meteorology and Climatology"                 
[25] " Oceanography"                                
[26] " Environmental Data Visualization"            
[27] " Invasive Species Management"                 
[28] " Wilderness First Responder"                  
[29] " Wilderness Policy and Practice"              
[30] " Research Seminar in Environmental Studies"   
[31] " Topics in Environmental Studies"             
[32] " Independent Study"                           
[33] " Environmental Studies Internship"            
[34] " Environmental Studies Capstone Experience"   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>credits <span class="ot">&lt;-</span> raw[,<span class="dv">3</span>]</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>credits <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(credits, <span class="st">"Hours"</span>, <span class="st">""</span>)</span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a>credits <span class="ot">&lt;-</span> <span class="fu">str_trim</span>( credits )</span>
<span id="cb147-4"><a href="#cb147-4" aria-hidden="true" tabindex="-1"></a>credits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "3"   "3"   "3"   "3"   "3"   "2"   "1-4" "3"   "3"   "3"   "3"   "3"  
[13] "3"   "3"   "3"   "3"   "4"   "3"   "3"   "3"   "3"   "3"   "1-4" "3"  
[25] "3"   "3"   "3"   "3"   "3"   "3"   "1-4" "1-3" "1-3" "0"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>( program, code, title, credits) <span class="ot">-&gt;</span> df </span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   program               code          title             credits         
 Length:34          Min.   :101.0   Length:34          Length:34         
 Class :character   1st Qu.:303.2   Class :character   Class :character  
 Mode  :character   Median :349.0   Mode  :character   Mode  :character  
                    Mean   :346.4                                        
                    3rd Qu.:418.5                                        
                    Max.   :499.0                                        </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  program code                                     title credits
1    ENVS  101   Introduction to Environmental Studies I       3
2    ENVS  102  Introduction to Environmental Studies II       3
3    ENVS  105                          Physical Geology       3
4    ENVS  201                      Earth System Science       3
5    ENVS  260                        Outdoor Leadership       3
6    ENVS  265         Paths to Environmental Leadership       2</code></pre>
</div>
</div>
</section>
</section>
<section id="extra-credit" class="level2">
<h2 class="anchored" data-anchor-id="extra-credit">Extra Credit</h2>
<p>Let’s close by doing something fun. Let’s make a wordcloud of the titles from ENVS classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_split</span>( title, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] ""              "Introduction"  "to"            "Environmental"
[5] "Studies"       "I"            

[[2]]
[1] ""              "Introduction"  "to"            "Environmental"
[5] "Studies"       "II"           

[[3]]
[1] ""         "Physical" "Geology" 

[[4]]
[1] ""        "Earth"   "System"  "Science"

[[5]]
[1] ""           "Outdoor"    "Leadership"

[[6]]
[1] ""              "Paths"         "to"            "Environmental"
[5] "Leadership"   

[[7]]
[1] ""              "Special"       "Topics"        "in"           
[5] "Environmental" "Studies"      

[[8]]
[1] ""            "Sustainable" "Societies:"  "James"       "River"      
[6] "Basin"      

[[9]]
[1] ""             "Introduction" "to"           "Meteorology" 

[[10]]
[1] ""             "Introduction" "to"           "Oceanography"

[[11]]
[1] ""            "Politics"    "of"          "the"         "Environment"

[[12]]
[1] ""            "Energy"      "and"         "the"         "Environment"

[[13]]
[1] ""            "Cartography"

[[14]]
[1] ""              "Environmental" "Pollution"    

[[15]]
[1] ""              "Environmental" "Management"   

[[16]]
[1] ""              "Environmental" "Geology"      

[[17]]
[1] ""         "Data"     "Literacy"

[[18]]
[1] ""      "Water"

[[19]]
[1] ""            "Outdoor"     "Programming" "and"         "Event"      
[6] "Management" 

[[20]]
[1] ""             "Outdoor"      "Team"         "Building"     "and"         
[6] "Group"        "Facilitation"

[[21]]
[1] ""        "Nature"  "Writing"

[[22]]
[1] ""             "Applications" "of"           "Conservation" "Science"     

[[23]]
[1] ""              "Special"       "Topics"        "in"           
[5] "Environmental" "Studies"      

[[24]]
[1] ""            "Meteorology" "and"         "Climatology"

[[25]]
[1] ""             "Oceanography"

[[26]]
[1] ""              "Environmental" "Data"          "Visualization"

[[27]]
[1] ""           "Invasive"   "Species"    "Management"

[[28]]
[1] ""           "Wilderness" "First"      "Responder" 

[[29]]
[1] ""           "Wilderness" "Policy"     "and"        "Practice"  

[[30]]
[1] ""              "Research"      "Seminar"       "in"           
[5] "Environmental" "Studies"      

[[31]]
[1] ""              "Topics"        "in"            "Environmental"
[5] "Studies"      

[[32]]
[1] ""            "Independent" "Study"      

[[33]]
[1] ""              "Environmental" "Studies"       "Internship"   

[[34]]
[1] ""              "Environmental" "Studies"       "Capstone"     
[5] "Experience"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_split</span>( title, <span class="st">" "</span>, <span class="at">simplify=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2]            [,3]          [,4]            [,5]           
 [1,] ""   "Introduction"  "to"          "Environmental" "Studies"      
 [2,] ""   "Introduction"  "to"          "Environmental" "Studies"      
 [3,] ""   "Physical"      "Geology"     ""              ""             
 [4,] ""   "Earth"         "System"      "Science"       ""             
 [5,] ""   "Outdoor"       "Leadership"  ""              ""             
 [6,] ""   "Paths"         "to"          "Environmental" "Leadership"   
 [7,] ""   "Special"       "Topics"      "in"            "Environmental"
 [8,] ""   "Sustainable"   "Societies:"  "James"         "River"        
 [9,] ""   "Introduction"  "to"          "Meteorology"   ""             
[10,] ""   "Introduction"  "to"          "Oceanography"  ""             
[11,] ""   "Politics"      "of"          "the"           "Environment"  
[12,] ""   "Energy"        "and"         "the"           "Environment"  
[13,] ""   "Cartography"   ""            ""              ""             
[14,] ""   "Environmental" "Pollution"   ""              ""             
[15,] ""   "Environmental" "Management"  ""              ""             
[16,] ""   "Environmental" "Geology"     ""              ""             
[17,] ""   "Data"          "Literacy"    ""              ""             
[18,] ""   "Water"         ""            ""              ""             
[19,] ""   "Outdoor"       "Programming" "and"           "Event"        
[20,] ""   "Outdoor"       "Team"        "Building"      "and"          
[21,] ""   "Nature"        "Writing"     ""              ""             
[22,] ""   "Applications"  "of"          "Conservation"  "Science"      
[23,] ""   "Special"       "Topics"      "in"            "Environmental"
[24,] ""   "Meteorology"   "and"         "Climatology"   ""             
[25,] ""   "Oceanography"  ""            ""              ""             
[26,] ""   "Environmental" "Data"        "Visualization" ""             
[27,] ""   "Invasive"      "Species"     "Management"    ""             
[28,] ""   "Wilderness"    "First"       "Responder"     ""             
[29,] ""   "Wilderness"    "Policy"      "and"           "Practice"     
[30,] ""   "Research"      "Seminar"     "in"            "Environmental"
[31,] ""   "Topics"        "in"          "Environmental" "Studies"      
[32,] ""   "Independent"   "Study"       ""              ""             
[33,] ""   "Environmental" "Studies"     "Internship"    ""             
[34,] ""   "Environmental" "Studies"     "Capstone"      "Experience"   
      [,6]         [,7]          
 [1,] "I"          ""            
 [2,] "II"         ""            
 [3,] ""           ""            
 [4,] ""           ""            
 [5,] ""           ""            
 [6,] ""           ""            
 [7,] "Studies"    ""            
 [8,] "Basin"      ""            
 [9,] ""           ""            
[10,] ""           ""            
[11,] ""           ""            
[12,] ""           ""            
[13,] ""           ""            
[14,] ""           ""            
[15,] ""           ""            
[16,] ""           ""            
[17,] ""           ""            
[18,] ""           ""            
[19,] "Management" ""            
[20,] "Group"      "Facilitation"
[21,] ""           ""            
[22,] ""           ""            
[23,] "Studies"    ""            
[24,] ""           ""            
[25,] ""           ""            
[26,] ""           ""            
[27,] ""           ""            
[28,] ""           ""            
[29,] ""           ""            
[30,] "Studies"    ""            
[31,] ""           ""            
[32,] ""           ""            
[33,] ""           ""            
[34,] ""           ""            </code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.vector</span>( <span class="fu">str_split</span>( title, <span class="st">" "</span>, <span class="at">simplify=</span><span class="cn">TRUE</span>) ) <span class="ot">-&gt;</span> words</span>
<span id="cb157-2"><a href="#cb157-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-3"><a href="#cb157-3" aria-hidden="true" tabindex="-1"></a>words <span class="ot">&lt;-</span> words[ <span class="fu">str_length</span>(words) <span class="sc">&gt;</span> <span class="dv">0</span> ]</span>
<span id="cb157-4"><a href="#cb157-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-5"><a href="#cb157-5" aria-hidden="true" tabindex="-1"></a>words <span class="ot">&lt;-</span> <span class="fu">sort</span>( words )</span>
<span id="cb157-6"><a href="#cb157-6" aria-hidden="true" tabindex="-1"></a>words</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "and"           "and"           "and"           "and"          
  [5] "and"           "Applications"  "Basin"         "Building"     
  [9] "Capstone"      "Cartography"   "Climatology"   "Conservation" 
 [13] "Data"          "Data"          "Earth"         "Energy"       
 [17] "Environment"   "Environment"   "Environmental" "Environmental"
 [21] "Environmental" "Environmental" "Environmental" "Environmental"
 [25] "Environmental" "Environmental" "Environmental" "Environmental"
 [29] "Environmental" "Environmental" "Environmental" "Event"        
 [33] "Experience"    "Facilitation"  "First"         "Geology"      
 [37] "Geology"       "Group"         "I"             "II"           
 [41] "in"            "in"            "in"            "in"           
 [45] "Independent"   "Internship"    "Introduction"  "Introduction" 
 [49] "Introduction"  "Introduction"  "Invasive"      "James"        
 [53] "Leadership"    "Leadership"    "Literacy"      "Management"   
 [57] "Management"    "Management"    "Meteorology"   "Meteorology"  
 [61] "Nature"        "Oceanography"  "Oceanography"  "of"           
 [65] "of"            "Outdoor"       "Outdoor"       "Outdoor"      
 [69] "Paths"         "Physical"      "Policy"        "Politics"     
 [73] "Pollution"     "Practice"      "Programming"   "Research"     
 [77] "Responder"     "River"         "Science"       "Science"      
 [81] "Seminar"       "Societies:"    "Special"       "Special"      
 [85] "Species"       "Studies"       "Studies"       "Studies"      
 [89] "Studies"       "Studies"       "Studies"       "Studies"      
 [93] "Studies"       "Study"         "Sustainable"   "System"       
 [97] "Team"          "the"           "the"           "to"           
[101] "to"            "to"            "to"            "to"           
[105] "Topics"        "Topics"        "Topics"        "Visualization"
[109] "Water"         "Wilderness"    "Wilderness"    "Writing"      </code></pre>
</div>
</div>
<p>We need to have the data in the format of</p>
<p><code>Word | Count</code></p>
<p>so let’s use our <code>dplyr</code> skills.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>( words, <span class="at">count =</span> <span class="dv">1</span> ) <span class="sc">|&gt;</span> </span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">word =</span> <span class="fu">factor</span>( words ) ) <span class="sc">|&gt;</span> </span>
<span id="cb159-3"><a href="#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>( word ) <span class="sc">|&gt;</span></span>
<span id="cb159-4"><a href="#cb159-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>( <span class="at">freq =</span> <span class="fu">sum</span>( count )) <span class="sc">|&gt;</span> </span>
<span id="cb159-5"><a href="#cb159-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>( <span class="sc">-</span>freq ) <span class="ot">-&gt;</span> tdm </span>
<span id="cb159-6"><a href="#cb159-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-7"><a href="#cb159-7" aria-hidden="true" tabindex="-1"></a>tdm </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 62 × 2
   word           freq
   &lt;fct&gt;         &lt;dbl&gt;
 1 Environmental    13
 2 Studies           8
 3 and               5
 4 to                5
 5 in                4
 6 Introduction      4
 7 Management        3
 8 Outdoor           3
 9 Topics            3
10 Data              2
# ℹ 52 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>( <span class="sc">!</span><span class="fu">require</span>( wordcloud ) ) { </span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"wordcloud"</span>)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"wordcloud2"</span>)  <span class="co"># for more fancy</span></span>
<span id="cb161-4"><a href="#cb161-4" aria-hidden="true" tabindex="-1"></a>} </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: wordcloud</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: RColorBrewer</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( wordcloud )</span>
<span id="cb164-2"><a href="#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>( <span class="at">words =</span> tdm<span class="sc">$</span>word, </span>
<span id="cb164-3"><a href="#cb164-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">freq =</span> tdm<span class="sc">$</span>freq )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="text_narrative_files/figure-html/unnamed-chunk-78-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>( <span class="at">words =</span> tdm<span class="sc">$</span>word, </span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">freq =</span> tdm<span class="sc">$</span>freq,</span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">scale=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.25</span>) ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="text_narrative_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>( <span class="at">words =</span> tdm<span class="sc">$</span>word, </span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">freq =</span> tdm<span class="sc">$</span>freq,</span>
<span id="cb166-3"><a href="#cb166-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">scale=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb166-4"><a href="#cb166-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">min.freq =</span> <span class="dv">1</span> ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="text_narrative_files/figure-html/unnamed-chunk-80-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>( <span class="at">words =</span> tdm<span class="sc">$</span>word, </span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">freq =</span> tdm<span class="sc">$</span>freq,</span>
<span id="cb167-3"><a href="#cb167-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">scale=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb167-4"><a href="#cb167-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">min.freq =</span> <span class="dv">2</span> ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="text_narrative_files/figure-html/unnamed-chunk-81-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud</span>( <span class="at">words =</span> tdm<span class="sc">$</span>word, </span>
<span id="cb168-2"><a href="#cb168-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">freq =</span> tdm<span class="sc">$</span>freq,</span>
<span id="cb168-3"><a href="#cb168-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">scale=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.25</span>),</span>
<span id="cb168-4"><a href="#cb168-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">min.freq =</span> <span class="dv">2</span>,</span>
<span id="cb168-5"><a href="#cb168-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">colors =</span> <span class="fu">brewer.pal</span>(<span class="dv">8</span>,<span class="st">"Dark2"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="text_narrative_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( wordcloud2 )</span>
<span id="cb169-2"><a href="#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wordcloud2</span>(<span class="at">data =</span> tdm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="wordcloud2 html-widget html-fill-item" id="htmlwidget-45081ed9a446b637dbba" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-45081ed9a446b637dbba">{"x":{"word":["Environmental","Studies","and","to","in","Introduction","Management","Outdoor","Topics","Data","Environment","Geology","Leadership","Meteorology","Oceanography","of","Science","Special","the","Wilderness","Applications","Basin","Building","Capstone","Cartography","Climatology","Conservation","Earth","Energy","Event","Experience","Facilitation","First","Group","I","II","Independent","Internship","Invasive","James","Literacy","Nature","Paths","Physical","Policy","Politics","Pollution","Practice","Programming","Research","Responder","River","Seminar","Societies:","Species","Study","Sustainable","System","Team","Visualization","Water","Writing"],"freq":[13,8,5,5,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"fontFamily":"Segoe UI","fontWeight":"bold","color":"random-dark","minSize":0,"weightFactor":13.84615384615385,"backgroundColor":"white","gridSize":0,"minRotation":-0.7853981633974483,"maxRotation":0.7853981633974483,"shuffle":true,"rotateRatio":0.4,"shape":"circle","ellipticity":0.65,"figBase64":null,"hover":null},"evals":[],"jsHooks":{"render":[{"code":"function(el,x){\n                        console.log(123);\n                        if(!iii){\n                          window.location.reload();\n                          iii = False;\n\n                        }\n  }","data":null}]}}</script>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>